# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.




pipelines:
  branches:
   main:
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - pipe: rupareddy5/deploy-new:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR/src'
                API_TOKEN: $deployment_token
                DEPLOYMENT_ENV: 'test1'
                APP_BUILD_COMMAND: echo works
              
                
          
         
          
          
