# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.




pipelines:
  custom:
   custom-pipeline:
    - variables: 
      - name: INPUT_ACTION
        default: "upload"
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - if [[ ! -z "$APP_LOCATION" ]];
            then 
                APP="--app $APP_LOCATION "
            fi
          - if [[ ! -z "$API_LOCATION" ]];
            then
                API="--api $API_LOCATION "
            fi

          - if [[ ! -z "$OUTPUT_LOCATION" ]];
            then
                OUTPUT="--outputLocation $OUTPUT_LOCATION "
            fi

          - ARG=$APP$API$OUTPUT
          - cd /bin/staticsites/
          - ./StaticSitesClient --deploymentaction $INPUT_ACTION --apiToken $deployment_token "$ARG"
          
          
         
          
          
